apiVersion: ENC[AES256_GCM,data:jT4=,iv:Q1TohDG44O7DOs5807ym4LNj6gXVBB72KY9lKCjkbq0=,tag:SMJlfiQhf38Ez7ZFLgV7yg==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:9P4fGFKPN75bWFadsUyKOzfX8U2MAW8nF9O7+Nw2IOZVq6ViYUfTU1WLG6e0P6xbJSzlAuF5tjewaa4sqBhhcpxx+eWTBAThCIuGTlvanuCAGxEoBDaTWJiM5GFpwf9/q2yNSkAGlVj+IIXoXfvzcURhcVkRp+0x/roA13xpiXcVFHAUnfVJqEynDzcDXvp9txjZzzHWQbDk7kBS0Fdxdm/VakkYnpWPl6dtoem1FC51hwtlCiOhxJFUtUZRucnCCKu8FAKgagNUzyBCVu7zfUlSyxdjQKrhL9SUotWFTgcwPKiRU/ZYg4NnDaySaz54myum/bVqRNXJUmoB20K5QzHr7FoJquRfAqj94pOGwTgfjrF3aqk5gyfZhR83FTKgS6kyfMj2rz2USPMKI1No9b7MhCGgoqWk6M6CQAhIH3Dgua1X,iv:f2vck/lRBFHJseWVZ+x+qUMxlittvgKJKjfC2rGqJe0=,tag:UtsvdFdGJQt6XyO9PK7JYw==,type:str]
kind: ENC[AES256_GCM,data:etQyWA5a,iv:XHSTxSP0f/cFhuzyU/TBbHFqZICI+bGvwK5qtbuT4Vw=,tag:9jyuJFmDeqa7IVqBSmAH4w==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:rG0Csy+C2KSluQ==,iv:hTZ3Xs0FyG4JWPV/nCJWNQGOaTqgklon3HycyckWkAA=,tag:KuUQtbu1m+g7Mr/WlZeH1Q==,type:str]
    namespace: noel-coral-secrets-app-development
type: ENC[AES256_GCM,data:scPX1VeC6EtENDIQQwgG9QHS1FCwb5nq71ZXHKxd,iv:iRw8R+hRNiSaKuQHirRFSmTp3HFt5+qmbTcMzK4qNHw=,tag:GBKpslWfuEu17xUXRMy9Pg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-08T20:45:43Z"
    mac: ENC[AES256_GCM,data:sakFJfHb37CXo9AUBAbOB0jW5oIoBILtatY4fmT4C9nkzXlv9EPhQBSSmKz66mKSjAG1fOlVapxLk9xXrQ02OVoJFit9Mm4Hr2WPbEAuzRxWY0qVUEivu7llqbXgfm/YnTZHdWVlNIZpEACfzD23hSJ/bOFow1dWQU9sWoQW/2I=,iv:kuUXAEVKx1xbMafzG4zciTbq/oABb+vVBXYAHSSgVnc=,tag:+N3H1H3dEnb5HPWq0neYtw==,type:str]
    pgp:
        - created_at: "2022-04-08T20:45:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAw1+0SBtJvJqAQ/+Pw6fUYkowCdj3HawTbNGr0oLY3F+rQns0GrZmofNEVvD
            /ZQMTPgs7Xjrb8+O8EE8i+RkLY+VpsHr10q39qv/PBedbpms8S1Vs7b1hK5mVXmo
            uVg9wkSEndSplxpGIPdBMQoLHDImXQcFajTX0XVOdgTh7hUAQubh6ok6I8QA+b4I
            ld+cCVyiOWKmG90zPxTrIRM44Ovs0ZRLUsl/VWIAe4xucgvoqtO8+qPiwX5gfm1V
            Fd4IcmEbji5tFdy2nBWbVccKA5EMZacm4nN9SJm+hEfV+mK1m2rCX+KO0B30/z7s
            +3dXUfvOrrxmLBMQFe/Kt6grGzU9d4tlRsCqMHc9uXlKLggqQxhCOx81tRawI/co
            SqqXhg/9gaD3KTFhpyRHbwGjsyW4i1fv6k0HwSjzo9v2q/GC0hxeYBbDvyfrQPxa
            fPV5nE496bHxUdg+1yw9+jQu2JBAFS903rKEDSxG6B8O20VP7J7mpj/aPUR7SxEx
            UPjbPuX6iKbCz2wm91wm2scxI1FHnHweXUG8iyOjCNHWh4QqjCOT0seAkKLQ/s+K
            2q6a0KLx04lD5iGPmdHlEM2P0IF7F+9Oy6j5l2rE26IHlGbK/dO4WW3b/SVrd2/h
            XeEKd/sH2Ezrnm8JX7hJfUksfxgNSXRXQiENCpb9bRjNpvBr58flCDH7NOE9NwbS
            XAG1BXQAbH8ZGxLdhJcTsiQ/n91IUCVw28JbnupltdRShdGNfW/SDy64LQXx573S
            hgVaKg78dBZYB+1AEnSvcnlfjKYkRhgVdozSZ3fKF4VjpAh5vJE3LNUK4ksL
            =3qx+
            -----END PGP MESSAGE-----
          fp: 7DB6EF589A3D43370E06AF4D13C5845206955A89
    unencrypted_regex: ^(namespace)$
    version: 3.7.2
