apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../applications/coral-system/ManifestDeployments/prometheus
patches:
  - ../../../../../../applications/coral-system/ManifestDeployments/prometheus/patches/labels-coral-system.yaml
